In [29]:
## import all the libraries

from tensorflow.keras.preprocessing.text import one_hot

In [30]:
## saample sentences

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [31]:
## defining the vocabulory size

voc_size = 10000

In [32]:
## One Hot Representation for each of the words

one_hot_rep = [one_hot(words, voc_size)for words in sent]
one_hot_rep

[[5484, 5139, 9497, 3379],
 [5484, 5139, 9497, 7774],
 [5484, 3896, 9497, 5854],
 [3260, 9767, 8905, 9152, 6781],
 [3260, 9767, 8905, 9152, 1391],
 [3668, 5484, 3110, 9497, 4215],
 [5270, 1152, 1361, 9152]]

In [33]:
## Word Embedding representation

from tensorflow.keras.layers import Input, Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [34]:
## Providing padding to each array of sentences

sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 5484 5139 9497 3379]
 [   0    0    0    0 5484 5139 9497 7774]
 [   0    0    0    0 5484 3896 9497 5854]
 [   0    0    0 3260 9767 8905 9152 6781]
 [   0    0    0 3260 9767 8905 9152 1391]
 [   0    0    0 3668 5484 3110 9497 4215]
 [   0    0    0    0 5270 1152 1361 9152]]


In [35]:
## feature representation

dim = 10

In [36]:
model = Sequential([
    Input(shape=(sent_length,)),
    Embedding(voc_size, dim)
])

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [38]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


array([[[-0.02925376,  0.04608444, -0.00599273, -0.0191096 ,
         -0.01466615, -0.04561073, -0.03519122,  0.04556816,
         -0.01543919,  0.01850928],
        [-0.02925376,  0.04608444, -0.00599273, -0.0191096 ,
         -0.01466615, -0.04561073, -0.03519122,  0.04556816,
         -0.01543919,  0.01850928],
        [-0.02925376,  0.04608444, -0.00599273, -0.0191096 ,
         -0.01466615, -0.04561073, -0.03519122,  0.04556816,
         -0.01543919,  0.01850928],
        [-0.02925376,  0.04608444, -0.00599273, -0.0191096 ,
         -0.01466615, -0.04561073, -0.03519122,  0.04556816,
         -0.01543919,  0.01850928],
        [ 0.02932284,  0.01036061, -0.00523732, -0.03438368,
          0.02480534,  0.00863516,  0.04430811,  0.01894491,
         -0.02752198,  0.04983521],
        [ 0.03032906,  0.02307931, -0.04844851,  0.03832655,
         -0.04132537,  0.01114429, -0.04413986, -0.04742265,
         -0.02840238,  0.01403416],
        [-0.02585844,  0.03560239,  0.00681683, -0.0

In [39]:
embedded_docs[0]

array([   0,    0,    0,    0, 5484, 5139, 9497, 3379], dtype=int32)

In [40]:
import tensorflow as tf
import keras
import numpy as np

print("TensorFlow:", tf.__version__)
print("Keras:", keras.__version__)
print("NumPy:", np.__version__)

print(type(embedded_docs))
print(embedded_docs.shape)
print(type(embedded_docs[0]))
print(embedded_docs[0].shape)

TensorFlow: 2.21.0
Keras: 3.15.0
NumPy: 2.4.6
<class 'numpy.ndarray'>
(7, 8)
<class 'numpy.ndarray'>
(8,)


In [41]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[[-0.02925376,  0.04608444, -0.00599273, -0.0191096 ,
         -0.01466615, -0.04561073, -0.03519122,  0.04556816,
         -0.01543919,  0.01850928],
        [-0.02925376,  0.04608444, -0.00599273, -0.0191096 ,
         -0.01466615, -0.04561073, -0.03519122,  0.04556816,
         -0.01543919,  0.01850928],
        [-0.02925376,  0.04608444, -0.00599273, -0.0191096 ,
         -0.01466615, -0.04561073, -0.03519122,  0.04556816,
         -0.01543919,  0.01850928],
        [-0.02925376,  0.04608444, -0.00599273, -0.0191096 ,
         -0.01466615, -0.04561073, -0.03519122,  0.04556816,
         -0.01543919,  0.01850928],
        [ 0.02932284,  0.01036061, -0.00523732, -0.03438368,
          0.02480534,  0.00863516,  0.04430811,  0.01894491,
         -0.02752198,  0.04983521],
        [ 0.03032906,  0.02307931, -0.04844851,  0.03832655,
         -0.04132537,  0.01114429, -0.04413986, -0.04742265,
         -0.02840238,  0.01403416],
        [-0.02585844,  0.03560239,  0.00681683, -0.0

In [42]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[[-0.02925376,  0.04608444, -0.00599273, -0.0191096 ,
         -0.01466615, -0.04561073, -0.03519122,  0.04556816,
         -0.01543919,  0.01850928],
        [-0.02925376,  0.04608444, -0.00599273, -0.0191096 ,
         -0.01466615, -0.04561073, -0.03519122,  0.04556816,
         -0.01543919,  0.01850928],
        [-0.02925376,  0.04608444, -0.00599273, -0.0191096 ,
         -0.01466615, -0.04561073, -0.03519122,  0.04556816,
         -0.01543919,  0.01850928],
        [-0.02925376,  0.04608444, -0.00599273, -0.0191096 ,
         -0.01466615, -0.04561073, -0.03519122,  0.04556816,
         -0.01543919,  0.01850928],
        [ 0.02932284,  0.01036061, -0.00523732, -0.03438368,
          0.02480534,  0.00863516,  0.04430811,  0.01894491,
         -0.02752198,  0.04983521],
        [ 0.03032906,  0.02307931, -0.04844851,  0.03832655,
         -0.04132537,  0.01114429, -0.04413986, -0.04742265,
         -0.02840238,  0.01403416],
        [-0.02585844,  0.03560239,  0.00681683, -0.0