In [16]:
## import all the libraries

from tensorflow.keras.preprocessing.text import one_hot

In [17]:
## saample sentences

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [18]:
## defining the vocabulory size

voc_size = 10000

In [19]:
## One Hot Representation for each of the words

one_hot_rep = [one_hot(words, voc_size)for words in sent]
one_hot_rep

[[5484, 5139, 9497, 3379],
 [5484, 5139, 9497, 7774],
 [5484, 3896, 9497, 5854],
 [3260, 9767, 8905, 9152, 6781],
 [3260, 9767, 8905, 9152, 1391],
 [3668, 5484, 3110, 9497, 4215],
 [5270, 1152, 1361, 9152]]

In [20]:
## Word Embedding representation

from tensorflow.keras.layers import Input, Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [21]:
## Providing padding to each array of sentences

sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 5484 5139 9497 3379]
 [   0    0    0    0 5484 5139 9497 7774]
 [   0    0    0    0 5484 3896 9497 5854]
 [   0    0    0 3260 9767 8905 9152 6781]
 [   0    0    0 3260 9767 8905 9152 1391]
 [   0    0    0 3668 5484 3110 9497 4215]
 [   0    0    0    0 5270 1152 1361 9152]]


In [22]:
## feature representation

dim = 10

In [23]:
model = Sequential([
    Input(shape=(sent_length,)),
    Embedding(voc_size, dim)
])

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[[-0.03639759,  0.02525708,  0.01419164, -0.02741921,
          0.04431525,  0.0170351 ,  0.02119699,  0.03654763,
          0.04899812,  0.04597746],
        [-0.03639759,  0.02525708,  0.01419164, -0.02741921,
          0.04431525,  0.0170351 ,  0.02119699,  0.03654763,
          0.04899812,  0.04597746],
        [-0.03639759,  0.02525708,  0.01419164, -0.02741921,
          0.04431525,  0.0170351 ,  0.02119699,  0.03654763,
          0.04899812,  0.04597746],
        [-0.03639759,  0.02525708,  0.01419164, -0.02741921,
          0.04431525,  0.0170351 ,  0.02119699,  0.03654763,
          0.04899812,  0.04597746],
        [ 0.01434353, -0.03661213,  0.02961374, -0.01379185,
         -0.04967619, -0.03757306, -0.02991557, -0.04438061,
          0.0069545 , -0.02942905],
        [ 0.03166649, -0.04906646,  0.00707684, -0.04172271,
          0.03019693,  0.03490552,  0.00463393, -0.02586991,
         -0.04206481, -0.0396795 ],
        [ 0.02189603,  0.00173686,  0.03951547,  0.0

In [26]:
embedded_docs[0]

array([   0,    0,    0,    0, 5484, 5139, 9497, 3379], dtype=int32)

In [27]:
import tensorflow as tf
import keras
import numpy as np

print("TensorFlow:", tf.__version__)
print("Keras:", keras.__version__)
print("NumPy:", np.__version__)

print(type(embedded_docs))
print(embedded_docs.shape)
print(type(embedded_docs[0]))
print(embedded_docs[0].shape)

TensorFlow: 2.21.0
Keras: 3.15.0
NumPy: 2.4.6
<class 'numpy.ndarray'>
(7, 8)
<class 'numpy.ndarray'>
(8,)


In [28]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[[-0.03639759,  0.02525708,  0.01419164, -0.02741921,
          0.04431525,  0.0170351 ,  0.02119699,  0.03654763,
          0.04899812,  0.04597746],
        [-0.03639759,  0.02525708,  0.01419164, -0.02741921,
          0.04431525,  0.0170351 ,  0.02119699,  0.03654763,
          0.04899812,  0.04597746],
        [-0.03639759,  0.02525708,  0.01419164, -0.02741921,
          0.04431525,  0.0170351 ,  0.02119699,  0.03654763,
          0.04899812,  0.04597746],
        [-0.03639759,  0.02525708,  0.01419164, -0.02741921,
          0.04431525,  0.0170351 ,  0.02119699,  0.03654763,
          0.04899812,  0.04597746],
        [ 0.01434353, -0.03661213,  0.02961374, -0.01379185,
         -0.04967619, -0.03757306, -0.02991557, -0.04438061,
          0.0069545 , -0.02942905],
        [ 0.03166649, -0.04906646,  0.00707684, -0.04172271,
          0.03019693,  0.03490552,  0.00463393, -0.02586991,
         -0.04206481, -0.0396795 ],
        [ 0.02189603,  0.00173686,  0.03951547,  0.0